---
title: "Registration Data Analysis : Report"
author: "Shreya Suresh"
date: "5 June 2018"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r include=FALSE, message=FALSE, results='asis', echo=FALSE}
load_data <- function(){
  library(tidyverse)
  library(lubridate)

  user_data_df <- read_tsv("/home/evive/EDA/input/users_annon.csv",TRUE)
  elig_data_df <- readRDS("/home/evive/EDA/input/1033_1037_1039_elig_2018_06_04.rds.rds")
  elig_data_df1 <- readRDS("/home/evive/EDA/input/mini_elig_all.rds")
  elig_data_df <- rbind(elig_data_df,elig_data_df1)

  return(process_data(user_data_df, elig_data_df))
}

process_data <- function(user_data_df, elig_data_df){
  elig_data_df$EviveUUID <- gsub(x = elig_data_df$EviveUUID, 
                                 pattern = "^.*.csv:", replacement = "")
  colnames(elig_data_df)[1] <- "upin"
  elig_data_df$AgeGroup <- EviveUtil::get_age_groups(age_vector = elig_data_df$Age)
  merged_data_df <- left_join(user_data_df, elig_data_df, by= "upin")
  result <- get_client_stats(elig_data_df, merged_data_df)
  return(result)
}


get_client_stats <- function(elig_data_df, merged_data_df){
  client_codes <- c("1003","1011","1013","1029", "1021", "1030",
                    "1020", "1037", "1039","1031","1033")

  client_demo_stats <- list()

  for(i in seq_along(client_codes))
     client_demo_stats[[i]] <- get_demo_stats(elig_data_df,
                                             merged_data_df, client_codes[i])
  
   

  return(client_demo_stats)
}

get_demo_stats <- function(elig_data_df, merged_data_df, code){
  client_df <- filter(elig_data_df, ClientCode == code)
  client_merged_df <- filter(merged_data_df, ClientCode == code)
  demo_v <- c("AgeGroup", "Gender", "RelationshipCode",
              "PlanCode", "State", "Zip", "JobStatus")
  time_v <- c("month","time","year")
  client_demo_stats <- list()

  for(i in seq_along(demo_v)){
    client_demo_stats[[i]] <- get_stats(var = demo_v[i],
                                        df = client_df,
                                        merged_df = client_merged_df)
  }
  client_demo_stats[[i+1]] <- slice_by_time(merged_df = client_merged_df,
                                            time_unit = "month")
  client_demo_stats[[i+2]] <- slice_by_time(merged_df = client_merged_df,
                                            time_unit = "hour")
  client_demo_stats[[i+3]] <- get_registration_trend(client_merged_df = client_merged_df)
  client_demo_stats[[i+4]] <- get_login_trend(client_merged_df = client_merged_df)

  return(client_demo_stats)
}
```

```{r echo=FALSE}
get_stats <- function(var, df, merged_df){
  var_df <- merged_df %>% group_by(.dots = var) %>% summarise(Count = n())
  temp <- df %>% group_by(.dots = var) %>% summarise(Total = n())
  var_df <- merge(var_df, temp, by = var)
  var_df$Proportion <- c(var_df$Count / var_df$Total)
  print(knitr::kable(var_df, format = "markdown"))
  data.m <- reshape2::melt(var_df)
  plot1 <- ggplot2::ggplot(data.m, aes_string(var, "value"))  +
   geom_bar(aes(fill = variable), position = "dodge", stat="identity")
  
  plot(plot1)
  return(var_df)
}
```

```{r echo=FALSE,include=FALSE}

slice_by_time <- function(merged_df,time_unit){
 if(identical(time_unit,"month")){
   merged_df$Month <- month(merged_df$registration_date)
   temp <- merged_df %>% group_by(Month) %>% summarise(Count = n())
   ggplot2::ggplot(temp, aes(Month, Count)) +
     geom_bar(position = "dodge", stat="identity")
 }

  else if(identical(time_unit,"hour")){
    merged_df$Hour <- hour(merged_df$registration_date)
    #merged_df$Hour <- unlist(sapply(merged_df$registration_date, hour))
    temp <- merged_df %>% group_by(Hour) %>% summarise(Count = n())
    ggplot2::ggplot(data=temp, aes(x=Hour, y=Count)) +
      geom_bar(position = "dodge", stat="identity")
  }

  knitr::kable(temp)
  return(temp)
}

get_registration_trend <- function(client_merged_df){
  client_merged_df$Year <- year(client_merged_df$registration_date)
  temp <- client_merged_df %>% group_by(Year) %>% summarise(Count = n())
   m <- max(temp$Count)
  #plot(temp$Year, temp$Count, xlim = c(2015,2018), ylim = c(0,m),
   #    xlab = "Year", ylab = "Count", type = "o")
  knitr::kable(temp)
  return(temp)
}

get_login_trend <- function(client_merged_df){
  client_login <- client_merged_df %>% filter(lastlogin == registration_date) %>%
    summarise(Count = n())
  knitr::kable(client_login)
  
}
```


```{r echo = FALSE, message=FALSE}
result <- load_data()
```

